## Q1

In [31]:
def count_words():
	st=input('enter a string:\n ')
	word=[]
	word=st.split()
	freq=[word.count(i) for i in word]
	d1=dict(zip(word,freq))
	print('\ndictionary : ', d1)
	print('The no of words', len(d1.keys()))

In [32]:
count_words()

enter a string:
 Hi, my name is gautam and gautam is my name

dictionary :  {'Hi,': 1, 'my': 2, 'name': 2, 'is': 2, 'gautam': 2, 'and': 1}
The no of words 6


## Q2

In [26]:
from collections import Counter
import numpy as np

def non_zero(mat):
	d={(i,j):item
	   for i,sub in enumerate(mat)
	   for j,item in enumerate(sub)
	   if item!=0}
	return(d)

def read_order(mat):
	return (len(mat),len(mat[0]))

def add_matrices(d1,d2):
	d=Counter(d1)+Counter(d2)
	return dict(d)

def dict_to_mat(d):
	i,j=zip(*d.keys())
	arr=np.zeros((max(i)+1,max(j)+1),np.int32)
	np.add.at(arr,tuple((i,j)),tuple(d.values()))
	return arr

def matrix_prog(mat1,mat2):
	print('The order of the matrix is: ', read_order(mat1))
	print('The order of the matrix is: ', read_order(mat2))
	d1=non_zero(mat1)
	d2=non_zero(mat2)
	print('\nMatrix 1 in dict form is: ',d1)
	print('Matrix 2 in dict form is: ',d2)
	d=add_matrices(d1,d2)
	print('\nFinal added matrix is: ', d)
	print('\nNow we will convert this to a 2D matrix')
	mat=dict_to_mat(d)
	print('\nFinal Matrix : \n', mat)

In [27]:
mat1=[[0,1,0,2],[2,4,0,0],[3,0,0,4]]
mat2=[[0,6,0,7],[9,0,0,0],[11,0,0,7]]

In [28]:
matrix_prog(mat1,mat2)

The order of the matrix is:  (3, 4)
The order of the matrix is:  (3, 4)

Matrix 1 in dict form is:  {(0, 1): 1, (0, 3): 2, (1, 0): 2, (1, 1): 4, (2, 0): 3, (2, 3): 4}
Matrix 2 in dict form is:  {(0, 1): 6, (0, 3): 7, (1, 0): 9, (2, 0): 11, (2, 3): 7}

Final added matrix is:  {(0, 1): 7, (0, 3): 9, (1, 0): 11, (1, 1): 4, (2, 0): 14, (2, 3): 11}

Now we will convert this to a 2D matrix

Final Matrix : 
 [[ 0  7  0  9]
 [11  4  0  0]
 [14  0  0 11]]
